project:
  type: website
  output-dir: docs

website:
  theme: slate
  title: "Engineer Paradise"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Ideas.qmd
        text: Ideas
      - href: Projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    html-math-method: katex
    toc: true



