project:
  type: website
  output-dir: docs

website:
  title: "Engineering History"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Ideas.qmd
        text: Ideas
      - href: Projects.qmd
        text: Projects

format:
  html:
    theme: vapor
    css: styles.css
    html-math-method: katex
    toc: true



