project:
  type: website
  output-dir: docs

website:
  title: "Engineer_Paradise"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Ideas.qmd
      - Projects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



